# Generated by Django 4.1.3 on 2022-11-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_newprojectapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dfdfdd', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
